### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by yuanyuan12080317** [issacqzh/IRL_Table2Text#2]
Thanks for your sharing, but it  lacks evaluation documents

**Comment by issacqzh** [comment]
What do you mean by evaluation documents? The test set?

**Comment by yuanyuan12080317** [comment]
Thanks for your reply. it lacks
from pycocoevalcap.bleu.bleu import Bleu
from pycocoevalcap.rouge.rouge import Rouge

**Comment by issacqzh** [comment]
Please refer to https://github.com/tylin/coco-caption. I think you can directly clone "pycocoevalcap" folder to this repo.

**Comment by yuanyuan12080317** [comment]
Thank you so much for being so patient.

**Comment by yuanyuan12080317** [comment]
I have another problem:
 # answer = [tokenizer.convert_tokens_to_string(tokenizer.convert_ids_to_tokens(inputs["input_ids"][j][start_pos[j]:end_pos[j]])) for j in range(batch_size)]
        for k in range(batch_size):
            gt = gt_ans[k]
            pred = answer[k]
            xyz = get_overlap(gt, pred)
"answer" is not defined ,
Why did you comment all  "answer" out?

**Comment by issacqzh** [comment]
Note that the "benchmark_off_the_shelf" function is no longer maintained as it's an experiment and is not being called in the main model.

**Comment by yuanyuan12080317** [comment]
oh ，Thank you so much for being so patient. 
self.tagger = Ner(host='localhost',port=9199)
"Ner"is not defined ,What should I do about it?
What do I need to comment out?  thank you very very much!

**Comment by issacqzh** [comment]
Please pull again and "pip install sner".

**Comment by yuanyuan12080317** [comment]
Thanks.
Isn't this a local service?
And there's no import

**Comment by issacqzh** [comment]
Yes, but you can also launch it on your server. I just added the import at line 15. You can pull again.

**Comment by yuanyuan12080317** [comment]
Thanks for your reply very very much

**Comment by yuanyuan12080317** [comment]
when I try to train,    python main_rl.py  --cuda --mode 0
FileNotFoundError: [Errno 2] No such file or directory: 'fields.pkl'

**Comment by issacqzh** [comment]
added

**Comment by yuanyuan12080317** [comment]
Thank you very very much.

**Comment by yuanyuan12080317** [comment]
when I try to train：
Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertForQuestionAnswering: ['vocab_layer_norm.weight', 'vocab_layer_norm.bias', 'vocab_transform.weight', 'vocab_transform.bias', 'vocab_projector.bias', 'vocab_projector.weight']
- This IS expected if you are initializing DistilBertForQuestionAnswering from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertForQuestionAnswering from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of DistilBertForQuestionAnswering were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['qa_outputs.bias', 'qa_outputs.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

FileNotFoundError: [Errno 2] No such file or directory: './finetuned_qa_name/model_ep_15.pth'

**Comment by issacqzh** [comment]
We don't provide pre-trained models in this repo, but you can refer to the comments in the "extractor_models" main function to train QA models.

**Comment by yuanyuan12080317** [comment]
Ok，Thank  you so much for being so patient.

**Comment by yuanyuan12080317** [comment]
Will I see the local service NER results only when I complete my training？

**Comment by yuanyuan12080317** [comment]
When I try to run python extractor_models.py 
Traceback (most recent call last):
  File "extractor_models.py", line 597, in <module>
    prepare_cache_training_data("distil-bert", "name")
  File "extractor_models.py", line 184, in prepare_cache_training_data
    ans_start_token_id = inputs.char_to_token(0,ans_start_char_id)
  File "/home/zly/anaconda3/envs/py37/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 555, in char_to_token
    raise ValueError("char_to_token() is not available when using Python based tokenizers")
ValueError: char_to_token() is not available when using Python based tokenizers
Thanks for your reply

**Comment by yuanyuan12080317** [comment]
Can you help me? I am looking forward to your reply. It still has that problem

**Comment by issacqzh** [comment]
Resolved
